### ISSUE TITLE
[FEATURE REQUEST] Added export file feature

### ISSUE THREAD

**Issue by JunedSetiawan** [ramonrietdijk/livewire-tables#17]
Maybe build an export file feature, or can use third party assistance such as the Spatie package or other packages

**Comment by ramonrietdijk** [comment]
Hi @JunedSetiawan,

Thanks for the suggestion! I will definitely look into this.

**Comment by ramonrietdijk** [comment]
I've added the ability to create [exports](https://ramonrietdijk.github.io/livewire-tables/usage/exports.html) in version 3.1.0 :rocket:
