### ISSUE TITLE
Cannot filter model class

### ISSUE THREAD

**Issue by gixroq** [ramonrietdijk/livewire-tables#21]
In the model property definition.

How can I limit the data being extracted based on a given condition. 

For example I would like to do something like the following.

$model = Blog::where('year',2023)->get();

**Comment by ramonrietdijk** [comment]
Hi @gixroq!

You could either add a date filter or a select [filter](https://ramonrietdijk.github.io/livewire-tables/usage/filters.html#filter-types) containing the years to your table.

If you always want to filter the table with the current year, for example, the easiest way would be to override the `query` method.

```php
use Illuminate\Database\Eloquent\Builder;

protected function query(): Builder
{
    return parent::query()->where('blogs.year', now()->year);
}
```

Hope this helps!

**Comment by gixroq** [comment]
Thanks. That worked.

**Comment by htellez** [comment]
how i connect that method to $model

**Comment by htellez** [comment]
i did it so

**Comment by htellez** [comment]
i did it so

**Comment by htellez** [comment]
I did it so 

protected function query(): Builder

    {

        return parent::query()->where('users.estado', 1);

    }

    protected string $model = $this->query();

And I have this  error

 **expression contains invalid operations**

**Comment by ramonrietdijk** [comment]
Hi @htellez, the query will be based on the model. Just overriding the `query` method is enough.

**Comment by htellez** [comment]
Thanks Ramón

work fine, perfectly

**Comment by htellez** [comment]
Hello Ramon

How i can implement a modal in order to create a category, for example

**Comment by ramonrietdijk** [comment]
Hi @htellez, I recommend creating new issues instead of replying to older ones. Everyone will be notified while your question is not related to the original post.

Creating new data for the table, via a modal for example, is unfortunately out of the scope for this package. You can implement this any way you like. You may use [actions](https://ramonrietdijk.github.io/livewire-tables/usage/actions.html) to trigger a modal.
