### ISSUE TITLE
Re-order support would be amazing

### ISSUE THREAD

**Issue by ditsbroefs** [ramonrietdijk/livewire-tables#22]
Would be very nice if re-rodering, possibly using Livewire Sortable.js, was possible .

**Comment by ramonrietdijk** [comment]
Hi @ditsbroefs,

That would indeed be quite nice! Thanks for the idea, I'll look into this to see what's possible.

**Comment by ramonrietdijk** [comment]
Records can be [reordered](https://ramonrietdijk.github.io/livewire-tables/usage/reordering.html) in version 3.2.0 :rocket:
