### ISSUE TITLE
View Column

### ISSUE THREAD

**Issue by ditsbroefs** [ramonrietdijk/livewire-tables#25]
Another suggestion: in addition to asHtml() implement a 'View Column' column type where one can pass the name of a blade file.

**Comment by MianUsamaIjaz** [comment]
Column::make(__('Action'), function ($model)
{
    $test = view('partials.test', ['id' => $model->id])->render();
    return $test;
})->clickable(false)
->asHtml(),


then in blade
<a href="testwebsite.com">{{ $id }}</a>

Unfortunately, doing this make the entire row content hyperlink.

Trying to figure out how to remove hyperlink from other columns

**Comment by gixroq** [comment]
This is how I solved it


```
Column::make(__('Action'), function ($model)
{
    $test = view('partials.test', ['id' => $model->id])->render();
    return $test;
})->asHtml(),
```


then in blade

`
<a href="testwebsite.com">{{ $id }}</a>
`

Unfortunately, doing this makes the entire row content hyperlinked.
Trying to figure out how to remove the hyperlink from other columns

**Comment by ditsbroefs** [comment]
I did something similar:
`
    Column::make(__(''), function (mixed $value, Model $model): string {
            return view('admin.fields.table.actions', $model)->render();
         })->clickable(false)->asHtml(),
`

**Comment by ditsbroefs** [comment]
I did something similar:

`
Column::make(__(''), function (mixed $value, Model $model): string {
        return view('admin.fields.table.actions', $model)->render();
    })->clickable(false)->asHtml(),
`

And then in my view:

`
<div class="flex justify-end space-x-1">
    @can('fields.edit')
        <div
            wire:click="edit({{ $id }})"
            title="Edit"
            class="leading-none bg-slate-50 hover:bg-slate-100 border p-2 pt-1"
        >
            <x-heroicon-o-pencil class="inline w-4 h-4 text-ivanhoe_gunmetal-700 font-bold cursor-pointer" />
        </div>
    @endcan
    @can('fields.delete')
        <div
            wire:click="delete({{ $id }})"
            title="Delete"
            class="leading-none bg-ivanhoe_red-500 hover:bg-ivanhoe_red-600 border p-2 pt-1"
        >
            <x-heroicon-o-trash class="inline w-4 h-4 text-white font-bold cursor-pointer" />
        </div>
    @endcan
</div>
`

But it would be elegant if one could just do:

`
ViewColumn::make(__(''), 'admin.fields.table.actions'),
`

**Comment by ramonrietdijk** [comment]
I've added the [ViewColumn](https://ramonrietdijk.github.io/livewire-tables/usage/columns.html#view-column) in version 3.3.0 to have more eloquent code :rocket:

**Comment by MianUsamaIjaz** [comment]
Awesome

**Comment by ditsbroefs** [comment]
Fantastic!
