### ISSUE TITLE
Feature Request: Add row selection options

### ISSUE THREAD

**Issue by KenKodz** [ramonrietdijk/livewire-tables#31]
Being able to select multiple rows is a great feature to have but could be improved upon. 

Sometimes selecting rows is not needed at all and would be great if it could be turned off as simply as Reordering. If there is nothing for a user to do when the rows are selected, then it can be confusing to users as to why they can select them in the first place.

Also, if it is enabled, there are times where you might want to specify the number of rows that are allowed to be selected. Having a property that specifies the maximum number of rows would be great to have.

**Comment by ramonrietdijk** [comment]
Hi @KenKodz,

I think it would be great to have more control over the selection, thanks for the suggestion!

**Comment by ramonrietdijk** [comment]
I've implemented the ability to [disable the selection](https://ramonrietdijk.github.io/livewire-tables/configuration/selection.html) in version 3.4.0 :rocket: 

I did leave out the selection of a maximum number of rows as I think it is beyond the scope of this package.
