### ISSUE TITLE
Pull Related Records of a Model as the Base Results

### ISSUE THREAD

**Issue by KenKodz** [ramonrietdijk/livewire-tables#34]
I want to create a table that has a base dataset of all the child records of the specific model that is loaded via Model-Route binding. I don't see a way to do this. Perhaps I am overlooking something.

For example, a phone with the `id` of 32 has multiple accounts (lines) configured to it. When the user views the phone's configuration (/phone/32), I want to show a table of all the accounts associated with that specific phone and no others. 

Any ideas on how I can accomplish this?

**Comment by KenKodz** [comment]
I gave up too soon. This is what I ended up doing. Let me know if there is a better way.

```php

    public int $phone_id;

    public function mount(): void
    {
        parent::mount();

        $this->phone_id = request('phone');
    }

    protected function query(): Builder
    {
        return $this->model()->query()->where('id', $this->phone_id);
    }
```

**Comment by ramonrietdijk** [comment]
Hi @KenKodz,

This is exactly how it can be implemented! You could even skip the `mount` method if you pass it on through the view.

```blade
<livewire:phone.lines.table :phone_id="..." />
```

In that case, the `phone_id` will automatically be assigned to your public property and only overriding the `query` method is needed.

Nonetheless, some documentation about this process would have been nice.
