### ISSUE TITLE
Feature Request: Support Project Through GitHub Sponsors

### ISSUE THREAD

**Issue by KenKodz** [ramonrietdijk/livewire-tables#39]
I'd like the ability to donate some money to help support this project. It might only be enough for a cup of coffee or a cool brew, but I'd like to show my appreciation for your work here. Perhaps you can turn on GitHub Sponsors.

**Comment by ramonrietdijk** [comment]
Hi @KenKodz,

Thank you very much for considering donating for my contributions! The request for GitHub Sponsors is currently awaiting approval :wink:

**Comment by ramonrietdijk** [comment]
The request has been approved! :tada:
