### ISSUE TITLE
Question: How to pass data to views

### ISSUE THREAD

**Issue by Omranic** [ramonrietdijk/livewire-tables#40]
Hey there,

Is there a way to pass arbitrary data to views, something like:

```php
            ViewColumn::make(trans('lang.var'), 'namespace::view', ['variable' => 'Some Value']),
```

And inside `namespace::view` I use it like $variable?

**❓ If this is something not currently supported, are you open to add this feature?**

----

💡 **Why this is useful:** Passing arbitrary data to views, enhances the flexibility and promotes reusability of view components. This practice allows developers to inject dynamic data into views, facilitating the creation of more interactive, customized content without hard-coding values. It fosters a modular approach, where components can be customized on-the-fly based on different contexts or user interactions, promoting a cleaner, more maintainable codebase.

**Comment by ramonrietdijk** [comment]
Hi @Omranic,

Thanks for the idea! It's quite nice to be able to pass any custom data to the view.

I've added the ability to do so in version 3.5.0 :rocket: 

Data can be passed by using the `with` method with an array of a key value pair like so:

```php
ViewColumn::make(__('Actions'), 'actions')
    ->with('key', 'value'),
```

**Comment by Omranic** [comment]
Awesome, thanks for the swift response 🙌

How about extending this to other columns as well?

This still proves useful for other column types given they're rendering views at the end of the day. The `BaseColumn` could make use of this, and thus have this feature across the board, specially for people who are willing to roll up their sleeves and override the default views, thoughts?

**Comment by ramonrietdijk** [comment]
I personally like to have it scoped to the `ViewColumn` as the variables are directly used within the given view itself. I have thought about customization and have introduced [metadata](https://ramonrietdijk.github.io/livewire-tables/advanced/metadata.html) for this, which can be used on both columns and filters.

This way, any arbitrary data can still be passed to the template views when overriding them.

**Comment by Omranic** [comment]
Make sense, thanks for the clarification 👍
