### ISSUE TITLE
Question: Is there a way to hide a columns by default, and persist columns status?

### ISSUE THREAD

**Issue by Omranic** [ramonrietdijk/livewire-tables#42]
Hey there,

# Q1
Is there a way to hide columns by default?
Scenario: define columns but decide to hide some of them in the default display view, which the use can unhide through the table options.

# Q2
Also: is there a way to persist column status per session, or in browser localstorage, so that when they refresh the page or browse away and come back they can find their column selections as is, not being reset to the original state. Is this something possible, or planned?

**Comment by ramonrietdijk** [comment]
Hi @Omranic,

By default, all columns will be shown and there is no easy way to hide a few. I do really like the idea so I'm definitely going to add this to the package!

Having the table settings saved somewhere is quite nice as well. I will think about this too.

**Comment by KenKodz** [comment]
To go along with this, it would be really nice if you could make it so you can choose the size of the page to hide columns. It would be even nicer if you could make it so that the hidden columns could go to an "expanding row" that has a slot where we can design how to show that data.

This is a "wildest dreams" type of request. Really cool to have, but can live without.

**Comment by ramonrietdijk** [comment]
Hi!

I've just released version 3.6.0 with the ability to hide columns by default. For the sake of this package, I've kept it as simple as possible.

I will still explore the possibilities to persist table configurations.

**Comment by Omranic** [comment]
Awesome, that's good news. Thanks Ramon!

**Comment by ramonrietdijk** [comment]
Hi @Omranic,

I've added [session storage](https://ramonrietdijk.github.io/livewire-tables/configuration/session.html) to the tables. When enabled, it will save the column configuration in the session. You can also easily add more properties if you want to save more.

This functionality has been released in version 3.8.0 :rocket:

**Comment by Omranic** [comment]
That's amazing, thanks for implementing this nice feature 🙌
