### ISSUE TITLE
Feature Request: Add ability to add non-livewire buttons to the table's bar

### ISSUE THREAD

**Issue by KenKodz** [ramonrietdijk/livewire-tables#47]
It would be nice if there was a way to add a button (or an action to the action button) that would allow me to use JavaScript (specifically AlpineJS) instead of Livewire for the button's action. 

The use case is for things like showing a modal. While this is easy to do in Livewire, sometimes you don't want to have to send a request to the server just to make something visible.

I put some thought into how to do it. I thought about making another trait for `button`'s or just making changes to the `actions.blade.php` for `standalone` actions. but I just couldn't wrap my head around how I'd handle passing the JavaScript to it. Perhaps it's too early in the morning. lol

This is a LOW priority request as I am able to just use Livewire for it.

Thank you for building this and considering the requests that are coming in.

**Comment by ramonrietdijk** [comment]
Hi @KenKodz,

Great suggestion! Having the ability to directly execute JavaScript would be really nice. Especially if there is no need to communicate with the back end.

JavaScript can now be executed with actions in version 3.7.0 :rocket: 

See the [documentation](https://ramonrietdijk.github.io/livewire-tables/usage/actions.html#javascript) for more information!

**Comment by KenKodz** [comment]
You are awesome!
