### ISSUE TITLE
Feature Request: Slots

### ISSUE THREAD

**Issue by KenKodz** [ramonrietdijk/livewire-tables#50]
Would you be interested in adding slots to the table? 

For instance, `livewire-table::bar.bar` could have `x-slot:before-actions`, `x-slot:after-actions`, `x-slot:before-search`, `x-slot:after-search`, etc. This would allow for customization without having to publish the templates.

**Comment by KenKodz** [comment]
Well, this stinks. https://github.com/livewire/livewire/discussions/5846

It seems that this isn't possible in Livewire v3. I was trying to get it working and was getting flustered as to why it wasn't working. Guess this will have to wait until this is added to v3.

**Comment by ramonrietdijk** [comment]
Hi @KenKodz!

Slots could be useful to prevent having to publish the views. However, I do recommend publishing them. If the views are published, the table would always use the same views, despite what happens in the package. If I were to change some things in the default layout in a future update, it could potentially break existing tables. By renaming, moving or deleting slots it would suddenly remove user defined content which I don't really like. Keeping the slots backwards compatible could limit the ability to change the layout without a breaking release.

I can understand that updating the views could take some time, but it is the easiest way to maintain and expand this package. The views in this package can be used as is, but they also act as a template to add any custom requirements. This is the same reason why I haven't added any `classes` or `style` methods, as I recommend overriding the templates themselves for the most flexibility.

Nonetheless, thank you for your suggestions!
