### ISSUE TITLE
Question: any plans to support other Eloquent Relations?

### ISSUE THREAD

**Issue by Omranic** [ramonrietdijk/livewire-tables#53]
Question: any plans to support other Eloquent Relations?
- [Polymorphic Relationships](https://laravel.com/docs/10.x/eloquent-relationships#polymorphic-relationships)
- [Many To Many Relationships](https://laravel.com/docs/10.x/eloquent-relationships#many-to-many)

I'd love to help and support getting this implemented!

**Comment by ramonrietdijk** [comment]
Hi @Omranic,

Having support for more types of relationships would be ideal! In a perfect world, all eloquent relations would be supported, where possible. Currently, I believe using a [computed](https://ramonrietdijk.github.io/livewire-tables/usage/columns.html#computed) column is the only way to achieve this at the moment. I have not yet needed the mentioned relationships myself, so I'm not sure when I can get around to it.

**Comment by ramonrietdijk** [comment]
Hi @Omranic,

Here I am again. I've changed quite a lot but it should now be possible to use any relation you like in the table.

This functionality, together with JSON support, have been released in version 3.9.0 :rocket: 

Curious about your thoughts!
