### ISSUE TITLE
Enumerable $models in Action::make

### ISSUE THREAD

**Issue by DrewNeon** [ramonrietdijk/livewire-tables#56]
`Action::make(__('My Action'), 'my_action', function (Enumerable $models): void {
    //
}),`

Excuse me, how to pass selected rows into this `Enumerable $models` when declaring an Action?

**Comment by ramonrietdijk** [comment]
Hi @DrewNeon,

The third parameter is the callback of the action and it will be called by the package when it's executed. This means that the passed `$models` will always contain the selected records, unless you are working with [standalone](https://ramonrietdijk.github.io/livewire-tables/usage/actions.html#standalone) actions. You don't have to pass anything manually.

Hope this helps!

**Comment by DrewNeon** [comment]
> Hi @DrewNeon,
> 
> The third parameter is the callback of the action and it will be called by the package when it's executed. This means that the passed `$models` will always contain the selected records, unless you are working with [standalone](https://ramonrietdijk.github.io/livewire-tables/usage/actions.html#standalone) actions. You don't have to pass anything manually.
> 
> Hope this helps!

Thanks for your quick response!

My bad, just messed up collections with arrays.
